### ISSUE TITLE
Cambiar en la documentación las uri de post group/userid -> group/user/userid

### ISSUE THREAD

**Issue by ivasansan1** [alesanfe/TODOlist-API#33]

**Comment by alesanfe** [comment]
También groups/{groupId}/{taskId} a groups/{groupId}/task/{taskId}

![image](https://user-images.githubusercontent.com/72869496/169170865-27d5e224-203d-4582-86da-a849b82b2352.png)

**Comment by alesanfe** [comment]
No sé si sería buena idea comprobar el resto de URIs.
