### ISSUE TITLE
Test con JUnit4.

### ISSUE THREAD

**Issue by alesanfe** [alesanfe/TODOlist-API#7]
No se considerará finalizado hasta que peten un par de ellos y se arreglen los correspondientes errores.

- Recurso task:
   - Get 
      - [x] Solo .
      - [x] Comprobar un orden y el contrario.
      - [x] Comprobar si funciona el limit.
      - [x] Probar el offset
      - [x] Probar los campos fields
      - [x] Realizar los distintos filtrados simples (name, title, status, difficulty)
      - [x] Comprobar con uno, dos y tres parámetros (startDate, finishedDate, priority, duration).
   - POST 
      - [x] Solo.
      - [x] Introducir vacío aquellos campo que sean necesarios.
      - [x] Introducir campos incorrectos en la petición.
   - PUT
      - [x] Solo.
      - [x] No introducir la id de  la tarea.
      - [x] Introducir una tarea que no existe.
      - [x] Introducir campos incorrectos.
   - DELETE 
      - [x] Solo.
      - [x] Eliminar una tarea que no existe.

- Recurso user:
   - Get 
      - [x] Solo. 
      - [x] Comprobar un orden y el contrario.
      - [x] Comprobar si funciona el limit.
      - [x] Probar el offset.
      - [x] Probar los campos fields
      - [x] Realizar los distintos filtrados simples (name, surname, email, location)
      - [x] Comprobar con uno, dos y tres parámetros tasCompleted.
   - POST user
      - [x] Solo.
      - [x] Introducir vacío aquellos campo que sean necesarios.
      - [x] Introducir campos incorrectos en la petición.
   - PUT
      - [x] Solo.
      - [x] No introducir la id del usuario.
      - [x] Introducir un usuario que no existe.
      - [x] Introducir campos incorrectos.
   - DELETE user
      - [x] Solo.
      - [x] Eliminar un usuario que no existe.
   - POST task
      - [x] Solo.
      - [x] Para un usuario que no existe.
      - [x] Para una tarea que no existe. 
      - [x] Para un usuario que ya tiene esa tarea.
   - DELETE task
      - [x] Solo 
      - [x] Para un usuario que no existe.
      - [x] Para una tarea que no existe.
      - [x] Para un usuario que no tiene esa tarea.

- Recurso group:
   - Get 
      - [x] Solo. 
      - [x] Comprobar un orden y el contrario.
      - [x] Comprobar si funciona el limit.
      - [x] Probar el offset.
      - [x] Probar los campos fields.
      - [x] Realizar los distintos filtrados simples (name, description).
      - [x] Comprobar con uno, dos y tres parámetros (numTask, createdDate).
   - POST group
      - [x] Solo.
      - [x] Introducir vacío aquellos campo que sean necesarios.
      - [x] Introducir campos incorrectos en la petición.
   - PUT
      - [x] Solo.
      - [x] No introducir la id del grupo.
      - [x] Introducir un grupo que no existe.
      - [x] Introducir campos incorrectos.
   - DELETE 
      - [x] Solo.
      - [x] Eliminar un grupo que no existe.
   - POST user
      - [x] Solo.
      - [x] Para un grupo que no existe.
      - [x] Para un usario que no existe. 
      - [x] Para un grupo que ya tiene ese usuario.
   - DELETE user
      - [x] Solo. 
      - [x] Para un grupo que no existe.
      - [x] Para un usuario que no existe.
      - [x] Para un grupo que no tiene ese usuario.
   - POST task
      - [x] Solo.
      - [x] Para un grupo que no existe.
      - [x] Para una tarea que no existe. 
      - [x] Para un grupo que ya tiene esa tarea.
   - DELETE task
      - [x] Solo. 
      - [x] Para un grupo que no existe.
      - [x] Para una tarea que no existe.
      - [x] Para un grupo que no tiene esa tarea.
  
- Recurso GitHUb:
   - Get user
      - [x] Solo.
      - [x] Probar los campos fields (en el caso de ser añadidos).
      - [x] Probar para un usuario que no existe.
   - POST user
      - [x] Solo.
      - [x] Probar para un usuario que no existe.
   - Get task
      - [x] Solo .
      - [x] Probar los campos fields (en el caso de ser añadidos).
      - [x] Probar para un usuario que no existe.
      - [x] Probar para una tarea que no existe.
   - POST task
      - [x] Solo.
      - [x] Probar para un usuario que no existe.
      - [x] Probar para una tarea que no existe.

- Recurso Pokemon
   - Pendiente.

- Consistencia
   - [x] Si se elimina un usuario también se debe eliminar de los grupos.   
   - [x] Si se elimina una tarea se debe de eliminar de los usuarios y de los usuarios de los grupos.

**Comment by alesanfe** [comment]
Me imagino que al final se hará con Postman al no tener nada como referencia

**Comment by ivasansan1** [comment]
me imagino que si

**Comment by ivasansan1** [comment]
"Para un usuario que no tiene esa tarea." no da mensaje de error

**Comment by alesanfe** [comment]
En principio ya está solucionado.

**Comment by alesanfe** [comment]
Aunque viendo lo que se h dado en teoría, no sé si es correcto que se mande un error.

![image](https://user-images.githubusercontent.com/72869496/169022017-78d4db93-17be-49f5-b551-fd85d545d7f6.png)

Ahora, la primera vez que se ejecuta el DELETE borra la tarea y en la segunda genera un error.

**Comment by ivasansan1** [comment]
en los delate de group/Gn/task/Tn no salen mensajes de error, pero funcionan correctamente

**Comment by alesanfe** [comment]
No debe saltar un error ya que elimina de todos los usuarios del grupo una tarea, por lo tanto, es muy probable que alguno no la tenga.

**Comment by alesanfe** [comment]
Si acaso, se puede comprobar previamente si algún usuario del grupo contiene la tarea.

**Comment by alesanfe** [comment]
Queda probar el postman con el de la nube (por si sale error 500).

**Comment by alesanfe** [comment]
Al final, JUnit para Pokemon y GitHub (cuando pase todos los test de pokemon, realizar una grabación de código y test pasado por si cambian mucho el código).
